//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFingerprint
    {
        public int employee_number { get; set; }
        public byte[] thumb { get; set; }
        public byte[] index_finger { get; set; }
        public byte[] middle_finger { get; set; }
        public byte[] ring_finger { get; set; }
        public byte[] little_finger { get; set; }
    
        public virtual EmployeeAttendance EmployeeAttendance { get; set; }
    }
}
