//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeAttendance()
        {
            this.EmployeeFingerprints = new HashSet<EmployeeFingerprint>();
        }
    
        public int ID { get; set; }
        public int employee_number { get; set; }
        public string username { get; set; }
        public System.TimeSpan check_in { get; set; }
        public System.DateTime date { get; set; }
        public string department_ID { get; set; }
        public string station_ID { get; set; }
    
        public virtual AttendanceStatu AttendanceStatu { get; set; }
        public virtual Department Department { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFingerprint> EmployeeFingerprints { get; set; }
    }
}
