//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int ID { get; set; }
        public int employee_number { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string department { get; set; }
        public string station { get; set; }
        public byte[] fingerprint { get; set; }
        public byte[] signature { get; set; }
    
        public virtual EmployeeAttendance EmployeeAttendance { get; set; }
    }
}
